// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWiL4ZrnrNpDxPy6FPOzmCSEIEdLv9v9E',
    appId: '1:1062028064938:web:f9708a072d69222ef238d3',
    messagingSenderId: '1062028064938',
    projectId: 'aacademic-e5df3',
    authDomain: 'aacademic-e5df3.firebaseapp.com',
    databaseURL: 'https://aacademic-e5df3-default-rtdb.firebaseio.com',
    storageBucket: 'aacademic-e5df3.appspot.com',
    measurementId: 'G-KL8D3R3DBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm_zBl0x2aSk0MOVCd3sh3cjbh-RP1O2o',
    appId: '1:1062028064938:android:ed1d23cb889dff75f238d3',
    messagingSenderId: '1062028064938',
    projectId: 'aacademic-e5df3',
    databaseURL: 'https://aacademic-e5df3-default-rtdb.firebaseio.com',
    storageBucket: 'aacademic-e5df3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJSWl7e1FP93cK2PnIrkPfinrckIvVSSI',
    appId: '1:1062028064938:ios:a1f48345f4ac6811f238d3',
    messagingSenderId: '1062028064938',
    projectId: 'aacademic-e5df3',
    databaseURL: 'https://aacademic-e5df3-default-rtdb.firebaseio.com',
    storageBucket: 'aacademic-e5df3.appspot.com',
    iosClientId: '1062028064938-e4inidfj0v6eho6mm7r4n4u6qa4m821f.apps.googleusercontent.com',
    iosBundleId: 'com.example.aacademic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJSWl7e1FP93cK2PnIrkPfinrckIvVSSI',
    appId: '1:1062028064938:ios:a1f48345f4ac6811f238d3',
    messagingSenderId: '1062028064938',
    projectId: 'aacademic-e5df3',
    databaseURL: 'https://aacademic-e5df3-default-rtdb.firebaseio.com',
    storageBucket: 'aacademic-e5df3.appspot.com',
    iosClientId: '1062028064938-e4inidfj0v6eho6mm7r4n4u6qa4m821f.apps.googleusercontent.com',
    iosBundleId: 'com.example.aacademic',
  );
}
